apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hive-metastore
  name: hive-metastore
spec:
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - env:
            - name: DB_DRIVER
              value: postgres
            - name: IS_RESUME
              value: "true"
            - name: SERVICE_NAME
              value: metastore
            - name: SERVICE_OPTS
              value: >-
                -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgresql:5432/metastore_db
                -Djavax.jdo.option.ConnectionUserName=hive
                -Djavax.jdo.option.ConnectionPassword=password
          image: yonryzhu/hive:3.1.3
          name: hive-metastore
          ports:
            - containerPort: 9083
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
